### ISSUE TITLE
AttributeError: module 'PySide2.QtWidgets' has no attribute 'qApp'

### ISSUE THREAD

**Issue by mandralis** [chiefenne/PyAero#3]
Dear @chiefenne,

I get the following error when running python3 PyAero.py.

`Traceback (most recent call last):
  File "src/PyAero.py", line 303, in <module>
    main()
  File "src/PyAero.py", line 296, in main
    window = MainWindow(app, STYLE)
  File "src/PyAero.py", line 104, in __init__
    self.init_GUI()
  File "src/PyAero.py", line 119, in init_GUI
    menusTools.createMenus()
  File "/Users/yanni/git/PyAero/src/MenusTools.py", line 76, in createMenus
    self.createPullDown(menu, pulldown)
  File "/Users/yanni/git/PyAero/src/MenusTools.py", line 96, in createPullDown
    triggered=eval(handler))
  File "<string>", line 1, in <module>
AttributeError: module 'PySide2.QtWidgets' has no attribute 'qApp'
Python(4460,0x7fff66caddc0) malloc: *** error for object 0x102a42ed0: pointer being freed was not allocated
Python(4460,0x7fff66caddc0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    4460 abort      python3 src/PyAero.py`

I installed PySide2 via pip3 install PySide2. Thank you for any input on how to solve this.

**Comment by mandralis** [comment]
I found that downgrading to PySide==5.11.x worked.
